name: GitHub PreRelease

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]+.[0-9]+"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-pre-release:
    name: Create pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create PreRelease
        uses: ncipollo/release-action@v1
        with:
          name: PreRelease ${{ github.ref_name }}
          tag: ${{ github.ref }}
          draft: true
          prerelease: true
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}