name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Collect docker meta
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: madpeteguy/jenkins-docker-slave-trivy
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          outputs: type=docker
          tags: madpeteguy/jenkins-docker-slave-trivy:test
          labels: ${{ steps.docker-metadata.outputs.labels }}
      - name: Save docker image
        run: docker save -o docker-image.tar madpeteguy/jenkins-docker-slave-trivy:test
      - name: Upload docker-image.tar
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: docker-image.tar
          if-no-files-found: error
          retention-days: 1
  test-docker-image:
    name: Test docker image
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Download docker-image.tar
        uses: actions/download-artifact@v4
        with:
          name: docker-image
      - name: Load images
        run: docker load --input docker-image.tar
      - name: Test container up
        run: docker run --rm madpeteguy/jenkins-docker-slave-trivy:test hostname
      - name: Test trivy version
        run: docker run --rm -p 127.0.0.1:9924:22/tcp madpeteguy/jenkins-docker-slave-trivy:test sh -c "trivy --version"
      - name: Test trivy image
        run: docker run --rm -p 127.0.0.1:9924:22/tcp madpeteguy/jenkins-docker-slave-trivy:test sh -c "trivy image hello-world:latest"
  cleanup-artifacts:
    name: Cleanup artifacts
    runs-on: ubuntu-latest
    needs: [ build-docker-image, test-docker-image ]
    steps:
      - name: Cleanup docker-image.tar
        uses: geekyeggo/delete-artifact@v4
        with:
          name: docker-image